"""Criando relacionamente entre unidade e produto

Revision ID: 20052c1e82d9
Revises: a4411d7be574
Create Date: 2024-04-29 12:26:46.480716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20052c1e82d9'
down_revision = 'a4411d7be574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unidade', ['unidade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidade_id')

    op.drop_table('unidade')
    # ### end Alembic commands ###
